- project:
    queue: tripleo
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-openstack-unit-7.16-centos-9-stream:
            voting: false
        - tripleo-ci-centos-9-scenario004-standalone: &scen4_vars
            vars:
              build_container_images: true
              containers_base_image: registry.access.redhat.com/ubi9:latest
    gate:
      jobs:
        - puppet-openstack-unit-7.16-centos-9-stream:
            voting: false
        - tripleo-ci-centos-9-scenario004-standalone: *scen4_vars
